Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
============ RESTART: C:\Users\david\Downloads\tool\imag_list.py ============
cutters.png
plane.png
hammer.png
wrench.png
measure.png
plyers.png
>>> 
============ RESTART: C:\Users\david\Downloads\tool\imag_list.py ============
cutters.png
plane.png
hammer.png
wrench.png
measure.png
plyers.png

============ RESTART: C:\Users\david\Downloads\tool\imag_list.py ============
king_of_spades.png
jack_of_clubs.png
7_of_hearts
9_of_clubs
8_of_diamonds
7_of_hearts
Traceback (most recent call last):
  File "C:\Users\david\Downloads\tool\imag_list.py", line 23, in <module>
    photo=PhotoImage(file=photox[0])
  File "C:\Users\david\Python36\lib\tkinter\__init__.py", line 3539, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\david\Python36\lib\tkinter\__init__.py", line 3495, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "king_of_spades.png": no such file or directory
>>> 
